KatzDevTestOrg/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TR-{000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KatzDevTestOrg/force-app/main/default/objects/Transaction__c/fields/Total_Discount__c.field-meta.xml
<CustomField>
    <fullName>Total_Discount__c</fullName>
    <label>Total Discount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

KatzDevTestOrg/force-app/main/default/objects/Transaction__c/fields/Transaction_Cost__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Cost__c</fullName>
    <label>Transaction Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

KatzDevTestOrg/force-app/main/default/objects/Transaction__c/fields/Transaction_Count__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Count__c</fullName>
    <label>Transaction Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

KatzDevTestOrg/force-app/main/default/objects/Transaction_Item__c/Transaction_Item__c.object-meta.xml
<CustomObject>
    <label>Transaction Item</label>
    <nameField>
        <displayFormat>TI-{000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

KatzDevTestOrg/force-app/main/default/objects/Transaction_Item__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Transaction Items</relationshipLabel>
    <relationshipName>Transaction_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

KatzDevTestOrg/force-app/main/default/classes/TestDataFactory.cls
/**
 * @Author              : Tejas P
 * @description         : Test Data Factory class for All object
 * @Modification Log    :
 * -----------------------------------------------------------
 * Date             Author              Details
 * -----------------------------------------------------------
 * 30/03/2022       Tejas P           Created
 **/
@isTest
public class TestDataFactory {
    
  /**********************************************************************************************
    @description  This method is to create Transaction__c record for Test methods
    @param TransCount [Integer], TransCost [Decimal], TotDiscount [Decimal]
    @return Transaction__c
  **********************************************************************************************/
    Public Static Transaction__c createTransactionRecord(Integer TransCount, Decimal TransCost, Decimal TotDiscount){
        Transaction__c NewTran= New Transaction__c();
            NewTran.Transaction_Count__c  = TransCount;
            NewTran.Transaction_Cost__c= TransCost;
            NewTran.Total_Discount__c= TotDiscount;
        return NewTran;
    }
    
    /**********************************************************************************************
    @description  This method is to create Transaction_Item__c record for Test methods
    @param NewTran [Id], ItemCost [Decimal], ItemName [String]
    @return Transaction_Item__c
  **********************************************************************************************/
    Public Static Transaction_Item__c createTransactionItemRecord(Id NewTran, Decimal ItemCost, String ItemName){
        Transaction_Item__c NewTranItem =New Transaction_Item__c();
            NewTranItem.Transaction__c=NewTran;
            NewTranItem.Item_Cost__c=ItemCost;
            NewTranItem.Item_Name__c= ItemName;
        return NewTranItem;
    }
}